# Generated by Django 3.0.5 on 2020-04-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCreateQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10, verbose_name='SID')),
                ('user_name', models.CharField(max_length=15, verbose_name='USER_NAME')),
                ('dimage', models.CharField(max_length=10, verbose_name='IMAGE')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
