# Generated by Django 3.0.5 on 2020-04-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_usersreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersreg',
        ),
    ]
